### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by wismill**

### CODE REVIEW

**Comment by rspeer** [comment]
Right, apparently I pushed a half-finished refactor.

I actually had a commit that finishes the refactor, which I had neglected to push. I can tell your fixes are right because they're in my code too. Thanks for taking a look -- it's clear you understand the code, and you reminded me of the problem.

**Comment by wismill** [comment]
Hi there, when you plan to push this commit?

**Comment by rspeer** [comment]
It's already pushed as 729f1186, right?

**Comment by wismill** [comment]
Yes. I do not understand why, but I used 0588116d41282654e262cdf963018a9df08846bc instead of e191146e51b944953944eecac49f5e29223d696d (current head). Sorry for the noise.

**Pull request closed without merging**
